export const MAX_CHAT_ATTACHMENTS = 16;
export const MAX_WEBCHAT_WORKSPACE_UPLOAD_BYTES = 100 * 1024 * 1024;
export const MAX_CHAT_WORKSPACE_ATTACHMENTS_TOTAL_BYTES = MAX_WEBCHAT_WORKSPACE_UPLOAD_BYTES;
